export const QUERY_KEYS = {
  USER: 'user',
  ADMIN_USER_EDIT: 'admin-user-edit',
  ADMIN_ALL_PROBLEMS: 'admin-all-problems',
  ADMIN_ALL_ANNOUNCEMENTS: 'admin-all-announcements',
  ADMIN_ANNOUNCEMENT: 'admin-announcement',
  ADMIN_ALL_CLASSES: 'admin-all-classes',
  ADMIN_ALL_FAQS: 'admin-all-faqs',
  ADMIN_FAQ: 'admin-faq',
  FAQ: 'faq',
  ANNOUNCEMENT: 'announcement',
  CLASS: 'class',
  CLASS_PROBLEM: 'class-problem',
  CLASS_STUDENT: 'class-student',
  CLASS_TA: 'class-ta',
  CLASS_CONTEST: 'class-contest',
  CLASS_CONTEST_PROBLEM: 'class-contest-problem',
  CLASS_CONTEST_PROBLEM_SUBMISSION: 'class-contest-problem-submission',
};
